### ISSUE TITLE
Add support for properties

### ISSUE THREAD

**Issue by colonelpanic8** [rblaze/haskell-dbus#11]
@jmillikin @rblaze 
Is there a way to expose properties (as in org.freedesktop.DBus.Properties) in this library?

**Comment by rblaze** [comment]
I don't know which type of message client receives when property is being accessed. All supported message types are handled by dispatch (https://github.com/rblaze/haskell-dbus/blob/master/lib/DBus/Client.hs#L333), so my guess is unless property access is mapped to method calls, there is no way to expose them.
