### ISSUE TITLE
Add generateClientFromFile to Generation

### ISSUE THREAD

**Issue by colonelpanic8** [rblaze/haskell-dbus#21]
I implemented a useful function to actually generate a file from a client which is actually much safer than the current approach involving unsafePerformIO. This should be added to this libarary eventually:
https://github.com/IvanMalison/status-notifier-item/blob/738197e4dc56aa6bf7f3c99c0759e5b797540b0e/src/StatusNotifier/Util.hs#L28

**Comment by rblaze** [comment]
It looks you just replacing unsafePerformIO with runIO, right?

You probably don't need to rewrite generateFromFilePath in your code again: it seems to be doing the same thing. And my last change will break it anyway, parseXML now asks for lazy Text, not String.
