### ISSUE TITLE
Exporting a Signal

### ISSUE THREAD

**Issue by athanclark** [rblaze/haskell-dbus#3]
How can I tell dbus that I have a signal which I want to `emit` to? It appears that calls to `emit` aren't causing the interface to change in d-feet, so I'm wondering if I can export the signal somehow before attempting to call it. Any help with this would be tremendous, your library has already saved me a great deal of pain!

**Comment by rblaze** [comment]
Not mine, really. I took it over to fix a few build issues which were on my way.
I'm not very familiar with dbus workings. If you can provide pull request which will make Signal work for you, I'll happily merge it.

**Comment by athanclark** [comment]
Awesome, thank you. I am considering just writing bindings to sdbus - it's much more fully featured, and would provide a lot of stock features expected (I guess). I think it would technically be a different project than this though, because this is a pure implementation.

**Comment by colonelpanic8** [comment]
@athanclark 

The new interface in #12 supports this

**Comment by colonelpanic8** [comment]
@athanclark Not sure if you are still interested, but #15 now also supports the generation of functions for both emitting and registering on particular signals. The generated functions should guarantee type safety and handle mashalling into and out of Variant objects for you.

**Comment by colonelpanic8** [comment]
This was fixed in #12
