### ISSUE TITLE
Is it expected that Cabal files in the repo and on Hackage differ?

### ISSUE THREAD

**Issue by qrilka** [rblaze/haskell-dbus#33]
BTW there's also no tags for versions 1.2.2 and 1.2.3 in the repo.

**Comment by rblaze** [comment]
They are expected to differ in PVP restrictions, which "stack upload" manages for me.

**Comment by qrilka** [comment]
That's quite unexpected when you have different code but if feel free to close the ticket if you prefer it that way

**Comment by rblaze** [comment]
Hackage is a source of truth for packages. Git is just a working copy: could be broken, could be moved, etc.

1.2.2 and 1.2.3 are metadata-only updates, no code changes.
