### ISSUE TITLE
Add proxy module?

### ISSUE THREAD

**Issue by colonelpanic8** [rblaze/haskell-dbus#35]
I wrote a module that uses haskell-dbus to provide functions to proxy a dbus service under a different name a while ago (see https://github.com/IvanMalison/notifications-tray-icon/blob/master/src/DBus/Proxy.hs).

I'd like to use it in a new place now, so I'm going to have to pull it out of its current home. If you think its a good idea, I'd like to simply move it into this library itself, but if you'd rather not add it, I completely understand and I will simply make a new library.

What do you think?

**Comment by rblaze** [comment]
I think creating a new library would be the best option here. As far as I understand, this is an uncommon use case; not something I'd add to the base library.
