### ISSUE TITLE
Support for xml-conduit 1.9.x?

### ISSUE THREAD

**Issue by peti** [rblaze/haskell-dbus#36]
Hi,

we would like to update our package set for the openSUSE Linux distribution to include `xml-conduit-1.9.0.0`, but unfortunately `dbus` won't accept that new version as a build dependency. Therefore I wonder whether you have any plans to update `dbus` to support the most recent version of `xml-xonduit`?

Best regards
Peter

**Comment by rblaze** [comment]
Will do this week.

**Comment by rblaze** [comment]
Published dbus-1.2.8
