### ISSUE TITLE
Support multiple addresses for sessions

### ISSUE THREAD

**Issue by averelld** [rblaze/haskell-dbus#37]
An old issue brought up way back in jmillikin/haskell-dbus#7 is still affecting up for me, it would be great if multiple addresses (e.g. in DBUS_SESSION_BUS_ADDRESS) could be supported, either by just taking the first one (see patch in that issue), or actually trying them in order.

**Comment by rblaze** [comment]
Looks reasonable. I'll patch it up. Or feel free to submit a PR. Note that stackage builds are currently broken, until newer network and xml-conduit packages are pulled in.

**Comment by RubenAstudillo** [comment]
@averelld  Maybe it's easier for rblaze if you set up a PR. I can also do it if it bothersome for you.

**Comment by colonelpanic8** [comment]
@averelld @RubenAstudillo Yes, someone should make a PR. I'm also happy to do it if no one else wants to.

**Comment by RubenAstudillo** [comment]
I submitted a PR https://github.com/rblaze/haskell-dbus/pull/39 .

**Comment by RubenAstudillo** [comment]
The PR was merged!. @averelld should close this issue now.

**Comment by rblaze** [comment]
v1.2.11 published
