### ISSUE TITLE
Package revisions

### ISSUE THREAD

**Issue by vmchale** [rblaze/haskell-dbus#38]
Dbus 1.2.2 fails on hackage:

```
https://matrix.hackage.haskell.org/#/package/dbus
```

**Comment by rblaze** [comment]
I'm not sure what I can do about it. This is an old package which didn't restrict network version and is incompatible with network 3.x. Recent versions do a better job at version bounds.

**Comment by vmchale** [comment]
If you have upload access you can make a revision here :) https://hackage.haskell.org/package/dbus-1.2.2/dbus.cabal/edit

**Comment by rblaze** [comment]
Published new revision, let's hope I did it right.
