### ISSUE TITLE
Handle missing DBUS_SESSION_BUS_ADDRESS

### ISSUE THREAD

**Issue by rnhmjoj** [rblaze/haskell-dbus#45]
It [appears](https://github.com/systemd/systemd/issues/11293) systemd and dbus are moving away from setting `DBUS_SESSION_BUS_ADDRESS` by default. It was actually removed for some time but it had to be reintroduced because many software still rely on it.

Could you handle the case when it's not set?

**Comment by rblaze** [comment]
What's the best way to test this?

**Comment by rblaze** [comment]
Disregard this, I understand the issue now.

`connectSession` will fail without this env variable. `connectSystem` will fallback to `unix:path=/var/run/dbus/system_bus_socket`.

**Comment by rblaze** [comment]
It's up to app developers to handle errors, use `dbus-launch` or connect to a specific address using `connect` function. Nothing that library should do by itself.

**Comment by rnhmjoj** [comment]
> It's up to app developers to handle errors

But should `connectSession` throw an error here? I think it should try connecting to the default socket `XDG_RUNTIME_DIR/bus` before giving up.

**Comment by rblaze** [comment]
Good point, I'll add a fallback.

**Comment by rblaze** [comment]
Fixed in 80986928b18a0dbc1935c9f888d72a6be6326eab, dbus-1.2.13 published

**Comment by rnhmjoj** [comment]
Thank you!
