### ISSUE TITLE
matchAll instead of matchAny

### ISSUE THREAD

**Issue by jluttine** [rblaze/haskell-dbus#47]
Hi, thanks for this great package, I'm loving it! :+1:

This isn't a bug report nor a feature request. Just a minor thought I wanted to share. When building `MatchRule` as `matchAny {matchSender = ..., matchMember = ...}`, the rule is such that the signal must match *all* those conditions, not just *any* of them. But when read, it sounds a bit as if it would match if any of those conditions is met. Therefore, `matchAll` would sound like a more correct name to me. I had the impression that it's `matchAny` because one can use it as such without giving `matchSender` etc and then it's a rule that matches any signal. But the name `matchAll` also gives that impression that it matches all signals. But when given the match conditions, the code makes a bit more sense when read, at least to me.

Well, I might be missing something because I just started using the package. Even if this thought made sense, making such a change would break all packages using this package, so wouldn't make sense to implement such a change. But anyway, I just wanted to share the thought. Feel free to just close this issue.

**Comment by rblaze** [comment]
Naming is hard :( I'd probably use `def` to avoid all ambiguities, but John named it `matchAny`. You are right, renaming it will be a pain for everyone. Unless there is a significant API change, I'll keep it as is. Thanks for pointing this out!
