### ISSUE TITLE
Writing services?

### ISSUE THREAD

**Issue by arrowd** [rblaze/haskell-dbus#49]
I'd like to use `dbus` library to write a D-Bus service application.

Coming from QtDbus, I was expecting that the library should provide some way to transform `.xml` service specification into some boilerplate code. However, I can't find anything related in the documentation.

`DBus.Generation` looks somewhat related, but there is no documentation for this module.

**Comment by rblaze** [comment]
@IvanMalison  as an author of Generation module in its current shape, could you provide some docs or generated service examples? I'm not even sure if TH code works for servers; if I remember correctly, you wrote it for the client-side.

**Comment by colonelpanic8** [comment]
DBus.Generation is for the generation of client libs. There are several examples of its usage here: https://github.com/taffybar/taffybar/tree/master/src/System/Taffybar/DBus/Client

and here:

https://github.com/taffybar/status-notifier-item/blob/master/src/StatusNotifier/Item/Client.hs

I expect that what arrowd really wants is an example of how to write the server end of things.

I have a real world example here: https://github.com/taffybar/taffybar/blob/a1bec09a7dcc65490eac93163d8cdf55dd1c2cdd/src/System/Taffybar/DBus/Toggle.hs#L137

but it may not be the most instructive thing in the world.

It is also possible to generate a client lib without going in to xml at all and just using the specified interface for the server

**Comment by arrowd** [comment]
Thanks, @IvanMalison , than clears things a bit.

It seems, that what I'm asking is some TH that would produce a value like your `interface` from an XML spec. Am I right, that there is no such functionality at the moment?

**Comment by rblaze** [comment]
There is no support for server-side code generation. I'll gladly accept the PR. Closing this issue for now.

**Comment by colonelpanic8** [comment]
@arrowd As @rblaze said, the existing generation is for generation of the client side of things. I'm actually a bit confused about what you are even suggesting here -- I don't think its possible to generate a server for arbitrary method calls. How what it know what to do with the stuff it receives?

the dbus library WILL automatically PROVIDE the xml that corresponds to the requests it handles. If you want to make sure that you are properly implementing some spec, you might take a look at the xml it generates for your server and make sure it matches?

**Comment by arrowd** [comment]
We're seemingly having different understanding of the development workflow.

When I started developing my D-Bus application with Qt, I first wrote an .xml description file. Then I used Qt code generator that created C++ adaptor classes from the XML spec. The generated adaptors have C++ methods for each D-Bus method declared in the spec. Finally, I just inherit from the adaptor class in implement these methods.

Now I'm starting to understand that in Haskell a different approach is used. The spec is written in Haskell itself using a DSL and the XML spec is derived from that to be used by the client app. Am I correct?

**Comment by rblaze** [comment]
"Workflow" makes it sound like a well-thought decision, that it probably wasn't. It's just a way that fit the original author of the library 10 years ago and nobody cared to change since then.
I agree that starting with an IDL file is the right way to go, and I see a way to provide server-side code generation. But it's a relatively large effort. I'll be happy to review it but won't do it on my own.
