### ISSUE TITLE
Converting signal body to string?

### ISSUE THREAD

**Issue by jluttine** [rblaze/haskell-dbus#50]
Hi! This is a question, not an issue. If this is not the right place to ask, I hope you could point me to a better forum.

I'm writing a simple program which listens to DBus signals and executes a given (external) command/executable when a signal is received (https://github.com/jluttine/dbus-listen). I'd like to pass the body of the signal to the command as an environment variable. I'm trying to figure out how I could convert the signal body to a string so I could use that string as the value of the environment variable. Would you have any suggestions how to achieve this?

The body has type `[Variant]` so I could of course just use `show` but that seems quite bad.. The receiving side would get a lot of unnecessary `"Variant"` substrings and all type information is basically lost.

I read through the entire documentation but I just couldn't figure out any way to construct a decent function of type `[Variant] -> String` (or alternatively `[Variant] -> [String]` perhaps). I couldn't even find a way to access the raw signal body so that I could just forward it as it was received (if that is even possible in principle).

Any ideas?

**Comment by rblaze** [comment]
You can unpack `Variant` to `Value` and pattern-match on it.

```
printVariant :: Variant -> String
printVariant (Variant value) = go value
  where
    go (ValueAtom atom) = print atom
    go (ValueBytes bs) = print bs
    ...
```

**Comment by jluttine** [comment]
Thanks for the help! :+1:
