### ISSUE TITLE
Loosen bounds on Hackage

### ISSUE THREAD

**Issue by vmchale** [rblaze/haskell-dbus#52]
dbus 1.2.19 can build with latest bytestring and template-haskell without any modifications, which allows GHC 9.0.1

Cheers!

**Comment by rblaze** [comment]
I tried it in the ghc-9 branch a few days ago, run into zlib and cassava
not allowing base-2.15 yet. zlib was fixed, will check again on cassava
today.

**Comment by rblaze** [comment]
Released 1.2.21
