### ISSUE TITLE
Build failures in dbus 1.0.0 to 1.2.2 with GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [rblaze/haskell-dbus#53]
I just wanted to let you know that I've used my Hackage trustee permissions to push some Hackage revisions for `dbus` in order to prevent build failures with GHC 9.0.1, e.g.:

* http://hackage.haskell.org/package/dbus-1.0.0/revisions/
* http://hackage.haskell.org/package/dbus-1.2.2/revisions/

**Comment by rblaze** [comment]
Thanks! It is surprising someone still cares about old versions, but why not.

**Comment by sjakobi** [comment]
Yeah, I ran into some weird build plans while trying to build `git-annex` with GHC 9.0.1.
