### ISSUE TITLE
`dbus` 1.2.23 no longer supports GHC 8

### ISSUE THREAD

**Issue by elldritch** [rblaze/haskell-dbus#56]
This is caused by #55 bumping the version of Template Haskell. See also: [build failures on Hackage](https://hackage.haskell.org/package/dbus-1.2.23/reports/2).

I think the right solution is that either the version range on `template-haskell` needs to be loosened, or the supported versions of `base` need to be tightened to exclude older GHCs.

**Comment by rblaze** [comment]
`template-haskell` had a non-backward-compatible change, so the code wouldn't work with both new and old versions anymore. Does hackage use some `base`-based heuristics to detect GHC versions, ignoring all other bundled packages? There is no technical reason to tighten `base` bound but I can do it so that docs will be built.

**Comment by elldritch** [comment]
I'm not sure, but my guess is yes since I've seen other packages that only support newer versions of GHC that specified `base` constraints and whose documentation properly built.

I think there's also a manual process for uploading documentation, although I can't remember exactly how it works off the top of my head.

**Comment by rblaze** [comment]
Released 1.2.24 with base >= 4.16

**Comment by elldritch** [comment]
Hmm, it looks like docs are still failing to build: https://hackage.haskell.org/package/dbus-1.2.24/reports/1. I'm not sure what's going on here or how to convince Hackage to build these docs - AFAICT it seems to be trying to build docs on a machine that's not running a supported version of GHC.

**Comment by dminuoso** [comment]
I find it sad that support for older GHC was dropped this way. How isolated is the backwards breaking change? Couldn't we simply use CPP to support older versions?
