### ISSUE TITLE
dbus XML parser fails to parse XML documents with namespace extensions

### ISSUE THREAD

**Issue by tsirakisn** [rblaze/haskell-dbus#59]
The now deprecated dbus-core library was able to parse documents that introduced new namespaces. Specifically, ones that utilized the Dbus Spec (see below). I am getting a parse error when attempting to parse these same documents with this library. Removing them allows the parser to proceed.

Spec tag: `<node xmlns:tp="http://telepathy.freedesktop.org/wiki/DbusSpec#extensions-v0" name="/">`
Example of new namespace items: `<tp:docstring>`, `<tp:enumvalue>`, etc

Usage of parser that throws an error: `DBus.Introspection.Parse.parseXML "/" xml_file_contents`, where xml_file_contents is just the Text object read from the document.

Any insight to this? Thanks,

Niko

**Comment by rblaze** [comment]
The parser only looks for specific attributes and ignores all others, so it shouldn't be bothered by namespaces. Maybe xml-conduit requires some additional setup to handle this kind of document.

Can you make a minimal spec that makes the parser fail with namespaces? A fix would be even better, but I'll look into it when I have time.

**Comment by crogers1** [comment]
Hey rblaze, I work with tsirakisn.  A spec trimmed down and "examplified" from the code we're working with is described below, borrowing from telepathy for ```enum```:
```xml
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node xmlns:tp="http://telepathy.freedesktop.org/wiki/DbusSpec#extensions-v0" name="/">
  <tp:enum name="EX_ENUM" type="s">
    <tp:enumvalue suffix="EX1" value="ex1"/>
  </tp:enum>
  <interface name="my.example.interface">
    <method name="cool_method">
      <arg type="s" name="argin" direction="in"/>
    </method>
  </interface>
</node>
```
putting this through ```parseXML``` fails.  Dropping the ```enum``` block, and thus leaving only basic ```interface```, ```method```, and ```arg``` tags will allow ```parseXML``` to succeed.

Thanks for your time in looking at this.

**Comment by rblaze** [comment]
It has nothing to do with namespaces, at least in the test case.

[Here](https://github.com/rblaze/haskell-dbus/blob/master/lib/DBus/Introspection/Parse.hs#L49) the parser expects that node's child is either a child node or interface definition. `enum` is neither, so parsing fails.

Could you try replacing `X.many` with `X.many'` and see if it works for you?

**Comment by tsirakisn** [comment]
@rblaze appreciate the quick turnaround! I gave that change a try and it does indeed parse test document above but still fails to parse my files. Going to dig into this a bit and report back. Thanks again.

**Comment by tsirakisn** [comment]
Okay, after replacing a few more X.many's with the alternative, my files are parsing. I was initially concerned that ignoring the tags would introduce undesired behavior, but it seems that my binaries are behaving correctly somehow. I think those results are good enough to close this issue, at least for my purposes. Thanks for your help!

**Comment by rblaze** [comment]
I can patch the parser to make it skip over unknown elements if you send me the full XML file. It already skips unknown attributes and can skip unknown nodes as well.

Just to point out, the Introspection module is not required to operate the library. It is a codegen to produce a service stub. You can write one yourself and save the trouble.

**Comment by tsirakisn** [comment]
> I can patch the parser to make it skip over unknown elements if you send me the full XML file

I have it patched on my end, which is good enough for my purposes. Whether you decide to add formal support is up to you.

> Just to point out, the Introspection module is not required to operate the library. It is a codegen to produce a service stub. You can write one yourself and save the trouble.

Ack, good to know

**Comment by rblaze** [comment]
I'm closing this issue for now. Feel free to send a pull request if you want this fixed on my side.

**Comment by tsirakisn** [comment]
@rblaze I can submit it if you'd like the fix to be mainlined. I didn't think you'd want it to be.

**Comment by rblaze** [comment]
Why not? It is possible other people will run into the same problem.

**Comment by rblaze** [comment]
Could you also add a test case covering your changes? It will prevent breakages in the future, given this code path won't be widely used.

**Comment by tsirakisn** [comment]
Agreed, I just didn't know if this change in particular was the route you wanted to go for a formal fix (and I am definitely no Haskell expert). I have no problem submitting with a test case :+1:

**Comment by rblaze** [comment]
Closing inactive issue
