### ISSUE TITLE
Feature Request: expose the dbus unique client name

### ISSUE THREAD

**Issue by Dretch** [rblaze/haskell-dbus#61]
Motivation: the [xdg-desktop-portal API](https://flatpak.github.io/xdg-desktop-portal/#idm4777) requires that the user attach a signal handler to an object path of `/org/freedesktop/portal/desktop/request/$SENDER/$TOKEN`. `$SENDER` here is the unique client name.

Currently it looks like [connectWith](https://hackage.haskell.org/package/dbus-1.2.27/docs/src/DBus.Client.html#connectWith) ignores the client name that comes back from the "Hello" request. 

Maybe this is for performance reasons, but I don't know of any other safe way to obtain the client id (currently I am calling `ListNames` and assuming that the highest unique name is the one for the connection, but this seems very fragile).

There could perhaps be an alternative connection method that returns the unique client name? I'd be happy to send a PR if this is deemed acceptable.

Cheers

**Comment by rblaze** [comment]
Sure, please send a PR, and I'll be happy to merge it. Could you make sure it is backward-compatible?

**Comment by rblaze** [comment]
Uploaded v1.2.28

**Comment by Dretch** [comment]
Thanks!
