### ISSUE TITLE
Feature Request: unix socket file descriptor support

### ISSUE THREAD

**Issue by Dretch** [rblaze/haskell-dbus#64]
Currently file descriptors are just (de)serialized as regular integers. However, since file descriptors are an index into a per-process table, and d-bus normally operates between different processes, the file descriptors passed from one dbus client process will not normally make any sense on the receiving client process. Moreover this does not seem to be the way the dbus protocol is intended to be implemented.

The [spec](https://dbus.freedesktop.org/doc/dbus-specification.html) says that _"...file descriptors need to be transferred via platform specific mechanism out-of-band. They must be sent at the same time as part of the message itself. They may not be sent before the first byte of the message itself is transferred or after the last byte of the message itself."_.

In practice (i.e. the reference implementation), this seems to mean the following:
 - File descriptor passing is only supported for unix sockets (not TCP).
 - This uses a special feature that Unix sockets have for passing file descriptors (see e.g. https://blog.cloudflare.com/know-your-scm_rights/).
 - The file descriptors in the message itself are serialized as indices into the array of file descriptors that are passed in SCM_RIGHTS for that particular message (rather than indices into the per-process array)
 - Where a client wants to send/receive file descriptors they need to request permission during the connection process by sending "NEGOTIATE_UNIX_FD" and getting back "AGREE_UNIX_FD".

 This ticket is to request that unix-socket-fd-passing be supported in haskell-dbus-client.

I'd be happy to implement this myself, if this meets with approval. I have [some prototype code](https://github.com/rblaze/haskell-dbus/compare/master...Dretch:haskell-dbus:file-descriptors-prototype) to prove it works, but this needs a lot of finishing / cleaning up.

**Comment by rblaze** [comment]
Sure, if you send a pull request, I'll be happy to merge this feature.

**Comment by Dretch** [comment]
This is now implemented, thanks for merging and releasing @rblaze
